### ISSUE TITLE
kodi_audiodec_dll.h not found

### ISSUE THREAD

**Issue by StormTrooper** [xbmc/audiodecoder.nosefart#14]
I"m getting build errors on these audio decoders as a result of:

[addons] change audio decoder addon interface to new C++ style
https://github.com/xbmc/xbmc/commit/46fe0bd3f24f1c3694771f44f3565d5cc4bb53d5

/cmake/addons/build/audiodecoder.nosefart/src/NSFCodec.cpp:29:31: fatal error: kodi_audiodec_dll.h: No such file or directory
 #include "kodi_audiodec_dll.h"
                               ^
compilation terminated.

**Comment by notspiff** [comment]
Patience. All binary addons are being redesigned and i cba to update before
ifaces have stabilized.

14. jul. 2017 08:43 skrev "Greg McCarthy" <notifications@github.com>:

**Comment by olafhering** [comment]
This one works for me.
